<!DOCTYPE html>
<html>
<head>
  <link rel="icon" type="image/x-icon" href="images/logo.ico">
</head>
<style>
	.container {
		background-color: #f1f1f1;
	}
	.container .me {
		float: left;
		padding-right: 20px;
	}
	.about-inner {
		width: 50%;
		text-align: left;
		margin: auto;
		background-color: #d6d6d6;
		padding: 0px 100px;
	}
	.white-box-about {
		/*width: 100%;*/
		background-color: #fff;
		border: 1px solid grey;
		padding: 10px 10px;
	}

	.white-box-about .logo {
		width: 50%;
	}

	.number {
		padding-left: 25px;
	}

	h1, h2, h3 {
		color: #2d95df;
	}

	h1 {
		font-size: 50px;
		padding-top: 40px;
		margin-bottom: 20px;
		text-align: center;
	}

	h3, p {
		font-size: 18px !important;
	}

	ul, li {
		font-size: 18px;
	}

	h3 {
		margin-bottom: 0px;
		color: #000;
		font-weight: bold;
	}

	p {
		margin-top: 0px;
	}

	h2 {
		font-size: 38px;
	}

	@media screen and (max-width: 600px) {
		.about-inner {
			width: 100%;
			padding: 0px;
		}

		.container {
			padding: 0px 20px;
		}

		.img-container-about {
			display: flex;
		}

		.me {
			margin: auto;
			padding-top: 20px;
		}

		h1 {
			padding-top: 10px;
			text-align: center;
			font-size: 30px;
		}

		h3, p {
			font-size: 18px !important;
		}

		.white-box-about .logo {
		width: 100%;
		}

		.number {
			padding-left: 20px;
		}

		.inner-inner {
			margin: 0px 10px;
		}
	}
</style>
<body>
	
<?php include 'header.php';?>
<div class="container">
	<div class="about-inner">
		<div class="inner-inner">
			<h1>Your Personal Information</h1>
			<p><strong>Dealing with personal information</strong></p>
			<p style="margin-bottom: 0px;">In dealing with your personal information, Sunshine Specialist Supports staff will:</p>
			<ul style="margin-top: 0px;">
				<li>ensure privacy for all of our clients when you are meeting or discussing matters of a personal or sensitive nature to us</li>
				<li>only collect and store personal information that is necessary for the functioning of the organisation and its activities to implement your plan</li>
				<li>use fair and lawful ways to collect personal information</li>
				<li>collect personal information only by consent from that individual or their nominated decision maker</li>
				<li>ensure that people know what sort of personal information is held; what purposes it is held for; how it is collected, used, disclosed and who will have access to it</li>
				<li>ensure that any general information that is provided to third parties which may contain personal information is de-identified in such a way as to ensure anonymity</li>
				<li>obtain written consent from participants detailing who information can be collected from and disclosed to</li>
				<li>ensure that personal information collected or disclosed is accurate, complete and up-to-date, and provide access to any individual to review information or correct wrong information about themselves</li>
				<li>take reasonable steps to protect all personal information from misuse and loss and from unauthorised access, modification or disclosure</li>
				<li>destroy or permanently de-identify personal information that is no longer needed and/or after legal requirements for retaining documents have expired</li>
			</ul>
			<p style="margin-bottom: 0px;"><strong>Responsibilities for managing privacy - all Sunshine Specialist Supports staff are responsible for:</strong></p>
			<ul style="margin-top: 0px;">
				<li>The appropriate management of personal information to which they have access</li>
				<li>ensuring they are familiar with the Privacy Policy and administrative procedures for handling personal information</li>
				<li>ensuring that participants, clients and other relevant individuals are provided with information about their rights regarding privacy</li>
				<li>handling any queries or complaints about a privacy issue</li>
				<li>understanding the duty of disclosure requirements to report all incidents, potential incidents or disclosures that have the potential to place either the person disclosing the information or another individual at serious risk of harm or in contact with the criminal justice system*</li>
				<li>informing participants of this duty of disclosure protocol</li>
			</ul>
			<p>*what does duty of disclosure mean?  If we become aware of information either provided to us by you or about you, or if we become aware of information about a real or potential situation that places either yourself or another person at an unacceptable risk of harm or there is a high probability this information relates to illegal activities, we have a legal obligation to report this to the relevant authorities.  In some circumstances we can inform you of this as it is happening, however there are some circumstance where it may be unsafe to do so.</p>
			<h3>Emails and other written correspondence</h3>
			<p>All written correspondence generated by Sunshine Specialist Supports (letters, emails etc) will contain the following privacy statement in the footer:<br>

			Sunshine Specialist Supports takes information privacy seriously.  If you would like more information about how we apply privacy to your information, please ask for a copy of our Privacy Policy.<br><br>

			<strong>IMPORTANT:</strong> This e-mail is for the use of the intended recipient only and may contain information that is confidential. If you are not the intended recipient you are notified that any review, re-transmission, disclosure, dissemination or other use of, or taking of any action in reliance upon, this information is prohibited. If you have received this e-mail in error please notify the sender immediately and delete all electronic and hard copies of this transmission together with any attachments.</p>
			<h3>Privacy for interviews and personal discussions</h3>
			<p>At the initial meeting, participants and clients will be told what information is being collected, how their privacy will be protected and their rights in relation to this information.<br><br>

			To ensure privacy for participants when discussing sensitive or personal matters, Sunshine Specialist Supports will arrange to meet participants and clients in a private space located in the community, e.g. meeting room etc or at the participant’s home.<br><br>

			Sunshine Specialist Supports is committed to being flexible with meeting times to accommodate the individual needs of participants and clients and their preferences for privacy.</p>
		</div>

	       <div class="white-box-about">
	          <img src="images/live-logo.png" class="logo"><br>
	          <span class="number">0412 080 494</span>
	       </div>
	</div>
</div>
	
</body>
</html>